### ISSUE TITLE
preparation for publish

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/pdf-export-component#7]
I moved maybe everything files, related too our pdf functionality from showcase.
You should check everything after me:
folder structure
import structure, connection between files, etc...

when everything will be good - please run build and publish at npm.
then install this package at https://github.com/GroceriStar/react-print-pdf and recreate the logic that we had at showcase. this will be our major place to test pdf stuff. and when we'll need - we'll update our separated react package - reconnect it here, test and when everything will be perfect - we'll move it into showcase - and clean it up there...

**Comment by atherdon** [comment]
@vadim9999 Ok, then check this task. i didn't move DownloadPDFLink components, but i'm sure you'll figure it on your own

**Comment by atherdon** [comment]
again - i just move code by copy-paste - it wouldn't work well if we build it, so i cannot tell you that i move it completely, you know

**Comment by vadim9999** [comment]
@atherdon How can I fix this ?
```
~/javascript/work/pdf-export-component$ yarn run build
yarn run v1.12.3
$ babel src -d lib
/bin/sh: 1: babel: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by atherdon** [comment]
please notify me - when do you think everything is moved and connected into right way - so we can make a publish at npm

**Comment by atherdon** [comment]
try `yarn install` first

**Comment by vadim9999** [comment]
It's needed run with sudo. Ok, I built component. Can I make publish to npm?

**Comment by atherdon** [comment]
yes, please publish it, so we can import it into create-react-app project

**Comment by vadim9999** [comment]
@atherdon I can't undersand when I import 
```
import RenderLists3 from '@groceristar/pdf-export';
```
I get this error 
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Layout3View`.
```
when I import like this
```
 import RenderLists3 from './components/RenderLists/RenderLists3';
```
It's working fine

**Comment by atherdon** [comment]
hold on

**Comment by atherdon** [comment]
can you share with me a code link where i can review it?

**Comment by atherdon** [comment]
i think you should push some code, because i cannot find it(or maybe i miss something)

**Comment by atherdon** [comment]
and you see - this is an example why components should be rewritten from time to time.

**Comment by vadim9999** [comment]
It's in PR https://github.com/GroceriStar/react-print-pdf/pull/3/commits/35193ddfef99ddeeea3663cdee141163cbc556fe

**Comment by atherdon** [comment]
i think the major problem here - you making an assumption that if everything worked together at `showcase` before - then it will be working on this repos too. and this is also separation is important - because you see - it's acting differently - then it's not well done and when we'll redo it - we'll have less errors on main projects.

So my advice - go and test everything using small steps

**Comment by atherdon** [comment]
i think we should close this task, our major work was done.
sure, we still need to connect this package at showcase, but i created a separated task there: https://github.com/GroceriStar/showcase/issues/157
